openapi: 3.0.3
info:
    title: pokemon letters
    description: give a name and get back pokemon with same first letter
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /openapi.json:
        get:
            tags:
                - new_poke
            summary: Download ./gen/http/openapi.json
            operationId: new_poke#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /pokemon/{name}:
        get:
            tags:
                - new_poke
            summary: pokemon new_poke
            operationId: new_poke#pokemon
            parameters:
                - name: name
                  in: path
                  description: first name
                  required: true
                  schema:
                    type: string
                    description: first name
                    example: Omnis delectus id temporibus ratione ipsum natus.
                  example: Neque aut eaque.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Enim qui velit sed.
                            example: Id rerum nobis.
components: {}
tags:
    - name: new_poke
      description: return pokemon with same first letter as name
