openapi: 3.0.3
info:
    title: pokemon letters
    description: give a name and get back pokemon with same first letter
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /openapi.json:
        get:
            tags:
                - poke
            summary: Download ./gen/http/openapi.json
            operationId: poke#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /pokemon/{name}:
        get:
            tags:
                - poke
            summary: pokemon poke
            operationId: poke#pokemon
            parameters:
                - name: name
                  in: path
                  description: first name
                  required: true
                  schema:
                    type: string
                    description: first name
                    example: Et minus.
                  example: In perferendis enim.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Soluta quos ut praesentium et eum.
                            example: Expedita quos quam omnis voluptas ut quia.
components: {}
tags:
    - name: poke
      description: return pokemon with same first letter as name
